site_name: AIcloud_II
repo_name: AIcloud_II

site_description: >-
    AIcloud_II
    
nav:
    - 用户手册-视频配置: '用户手册-视频配置.md'
    - 用户手册-视频库: '用户手册-视频库.md'

        

# 选择主题，例如官方主题
theme: readthedocs

# 启用搜索功能
plugins:
  - search