site_name: TrafficFlowAICloud
repo_name: TrafficFlowAICloud

site_description: >-
    TrafficFlowAICloud
    
nav:
    - 首页: index.md
    - 用户手册-视频配置: '用户手册-视频配置.md'
    - 用户手册-视频库: '用户手册-视频库.md'

        

# 选择主题，例如官方主题
theme: readthedocs

# 启用搜索功能
plugins:
  - search